smart_web/smart_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Set the root URL to include the patterns from web_site.urls
    path("", include("web_site.urls")),

    # Include other URL patterns as needed
    path("admin/", admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smart_web/web_site/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path("", views.index, name="index"),
    path("index_es", views.index_es, name="index_es"),
    path("about", views.about, name="about"),
    path("about_es", views.about_es, name="about_es"),
    path("services", views.services, name="services"),
    path("services_es", views.services_es, name="services_es"),
    path("portfolio", views.portfolio, name="portfolio"),
    path("portfolio_es", views.portfolio_es, name="portfolio_es"),
    path("contact", views.contact, name="contact"),
    path("contact_es", views.contact_es, name="contact_es"),
    path("faqs", views.faqs, name="faqs"),
    path("faqs_es", views.faqs_es, name="faqs_es"),
    path("real_state_es", views.real_state_es, name="real_state_es"),
    path("real_state", views.real_state, name="real_state"),
    path("smart_investment", views.smart_investment, name="smart_investment"),
    path("smart_investment_es", views.smart_investment_es, name="smart_investment_es"),
    path("insurance_es", views.insurance_es, name="insurance_es"),
    path("insurance", views.insurance, name="insurance"),
    path("accountant", views.accountant, name="accountant"),
    path("accountant_es", views.accountant_es, name="accountant_es"),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smart_web/web_site/models.py
from django.db import models
from django.utils import timezone
import os

# Create your models here.

class SMRTPROPERTIES(models.Model):
    imb_ID = models.AutoField(primary_key=True, db_column='IMBID')
    imb_Category = models.CharField(max_length=60, null=True, db_column='IMBCATEGORY')
    imb_Name = models.CharField(max_length=120, null=True, db_column='IMBNAME')
    imb_MLS = models.FloatField(null=True, db_column='IMBMLS')
    imb_Type = models.CharField(max_length=50, null=True, db_column='IMBTYPE')
    imb_City = models.CharField(max_length=50, null=True, db_column='IMBCITY')
    imb_State = models.CharField(max_length=50, null=True, db_column='IMBSTATE')
    imb_Area = models.CharField(max_length=80, null=True, db_column='IMBAREA')
    imb_Bedrooms = models.SmallIntegerField(null=True, db_column='IMBBEDROOMS')
    imb_Bathrooms = models.SmallIntegerField(null=True, db_column='IMBBATHROOMS')
    imb_Size = models.FloatField(null=True, db_column='IMBSIZE')
    imb_Price = models.DecimalField(max_digits=12, decimal_places=2, null=True, db_column='IMBPRICE')
    imb_Currency = models.CharField(max_length=30, null=True, db_column='CURRENCY')
    imb_New_Flag = models.BooleanField(null=True, db_column='IMBNEWFLAG')
    imb_Owner = models.CharField(max_length=80, null=True, db_column='IMBOWNER')
    imb_Agent = models.CharField(max_length=80, null=True, db_column='IMBAGENT')
    imb_Prom_Disc = models.BooleanField(null=True, db_column='IMBPROMDISC')
    imb_Description = models.CharField(max_length=200, null=True, db_column='IMBDESCRIPTION')
    imb_Description_Es = models.CharField(max_length=200, null=True, db_column='IMBDESCRIPTIONES')
    imb_Active = models.BooleanField(null=True, db_column='IMBACTIVE')
    imb_Creation_Time = models.DateTimeField(default=timezone.now)
    

    def __str__(self):
        return f"{self.imb_ID} {self.imb_Name}"

    def save(self, *args, **kwargs):
        if self._state.adding:
            self.imb_Creation_Time = timezone.now()
        super().save(*args, **kwargs)

    class Meta:
        managed = True
        db_table = 'SMRTPROPERTIES'

def get_image_path(instance, filename):
        # Generate the folder path based on the property ID
        property_id = instance.property.imb_ID
        return f'property_images/{property_id}/{filename}'

class PropertyImage(models.Model):
    property = models.ForeignKey(SMRTPROPERTIES, on_delete=models.CASCADE, )  # Forward reference to SMRTPROPERTIES
    image = models.ImageField(upload_to=get_image_path, null=True, blank=True, db_column='IMAGES')

    class Meta:
        managed = True
        db_table = 'PROPERTYIMAGES'  # 


class SMRTWEBFORM(models.Model):
    frm_id = models.AutoField(primary_key=True, db_column='FRMID')
    frml_name = models.CharField(max_length=60, blank=True, null=True, db_column='FRMLNAME')
    frm_fname = models.CharField(max_length=60, blank=True, null=True, db_column='FRMFNAME')
    frm_phone = models.CharField(max_length=15, blank=True, null=True, db_column='FRMPHONE')
    frm_email = models.CharField(max_length=50, blank=True, null=True, db_column='FRMEMAIL')
    frm_serv = models.CharField(max_length=60, blank=True, null=True, db_column='FRMSERV')
    frm_messag = models.CharField(max_length=80, blank=True, null=True, db_column='FRMMESSAG')
    frm_fcont = models.BooleanField(blank=True, null=True, db_column='FRMFCONT')
    frm_date = models.DateTimeField(blank=True, null=True, db_column='FRMDATE')

    class Meta:
        managed = True
        db_table = 'SMRTWEBFORM'
        

def get_asociate_path(instance, filename):
    """
    Generates a unique path for the uploaded image based on associate name.
    """
    associate_name = instance.nombre.lower().replace(" ", "_")  # Sanitize name
    return os.path.join('asociates', associate_name, filename)

class Asociados(models.Model):
    nombre = models.CharField(max_length=255)
    contacto = models.CharField(max_length=255)
    area_expertis = models.CharField(max_length=255)
    puesto = models.CharField(max_length=255)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to=get_asociate_path, blank=True)  # Allow blank images
    activo = models.BooleanField(null=True)

    def __str__(self):
        return f"{self.nombre} ({self.area_expertis})"

    class Meta:
        managed = True

smart_web/web_site/views.py
from django.urls import reverse
from datetime import datetime
from django.http import HttpResponseRedirect
from django import forms
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import SMRTPROPERTIES, SMRTWEBFORM, PropertyImage, Asociados

 # Create your views here.



def index(request):
    if request.method == 'POST':
        form = SMRTWEBFORMForm(request.POST)
        if form.is_valid():
            form.instance.frm_date = datetime.now()
            form.save()
            # Redirect to a success page or another view after form submission
            return redirect('index')  # Redirect to the same view ('index') after form submission
    else:
        form = SMRTWEBFORMForm()
    
    return render(request, "web_site/index.html", {'form': form})

class SMRTWEBFORMForm(forms.ModelForm):
    frm_fcont = forms.BooleanField(initial=True, required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    
    # Define choices for 'serv' field
    SERVICE_CHOICES = [
        ('Bienes raices - Real State', 'Bienes raices - Real State'),
        ('Inversion - Investment', 'Inversion - Investment'),
        ('Seguros - Insurance', 'Seguros - Insurance'),
        ('Contabilidad - Contability', 'Contabilidad - Contability'),
    ]

    frm_serv = forms.MultipleChoiceField(
        choices=SERVICE_CHOICES,
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),  # Apply Bootstrap class
    )

    class Meta:
        model = SMRTWEBFORM
        exclude = ['frm_date']
        widgets = {
            'frml_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido - Surename'}),
            'frm_fname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre - Name'}),
            'frm_phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Teléfon - Telephone'}),
            'frm_email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico - Email'}),
            'frm_messag': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'placeholder': 'Mensaje - Message'}),
        }

def index_es(request):
    if request.method == 'POST':
        form = SMRTWEBFORMForm(request.POST)
        if form.is_valid():
            form.instance.frm_date = datetime.now()
            form.save()
            return redirect('index_es')  # Redirect to a success page
    else:
        form = SMRTWEBFORMForm()
    
    return render(request, "web_site/index_es.html", {'form': form})

def about(request):
   asociates = Asociados.objects.filter(activo=True)

   context = {"socios" : asociates       
    } 
   return render(request, "web_site/about.html", context)

def about_es(request):
   asociates = Asociados.objects.filter(activo=True)

   context = {"socios" : asociates       
    } 
   return render(request, "web_site/about_es.html", context)

def services(request):
   return render(request, "web_site/services.html")

def services_es(request):
   return render(request, "web_site/services_es.html")

def real_state_es(request):
   return render(request, "web_site/real_state_es.html")

def smart_investment_es(request):
   return render(request, "web_site/smart_investment_es.html")

def real_state(request):
   return render(request, "web_site/real_state.html")

def smart_investment(request):
   return render(request, "web_site/smart_investment.html")


def contact(request):
   if "data" not in request.session:

        # If not, create a new list
        request.session["data"] = []
   if request.method == 'POST':
      # Take in the data the user submitted and save it as form
      form = SMRTWEBFORMForm(request.POST)
       # Check if form data is valid (server-side)
      if form.is_valid():
         user = form.cleaned_data
         request.session["data"] += [user]
         return HttpResponseRedirect(reverse("contact"))
      else:

            # If the form is invalid, re-render the page with existing information.
            return render(request, "tasks/add.html", {
                "form": form, "data": request.session["data"]
            })

   return render(request, "web_site/contact.html", {
      "form": SMRTWEBFORMForm(), "data": request.session["data"]
   })

def portfolio(request):
    # Get images
    imgs = PropertyImage.objects.all()
    # Fetch distinct values for each dropdown
    cities = SMRTPROPERTIES.objects.filter(imb_Active=True).values_list('imb_City', flat=True).distinct()
    property_types = SMRTPROPERTIES.objects.filter(imb_Active=True).values_list('imb_Type', flat=True).distinct()

    # Filter properties based on user input
    active_props = SMRTPROPERTIES.objects.filter(imb_Active=True)

    if request.method == 'GET':
        # Get the filters from the request
        location_filter = request.GET.get('location_filter')  # Filter for location
        property_type_filter = request.GET.get('property_type_filter')  # Filter for property type
        bedroom_filter_min = request.GET.get('bedroom_filter_min')  # Minimum number of bedrooms
        bedroom_filter_max = request.GET.get('bedroom_filter_max')  # Maximum number of bedrooms

        # Apply filters one by one
        if location_filter:
            active_props = active_props.filter(imb_City=location_filter)
        if property_type_filter:
            active_props = active_props.filter(imb_Type=property_type_filter)
        if bedroom_filter_min:
            # Filter properties with number of bedrooms greater than or equal to the minimum specified
            active_props = active_props.filter(imb_Bedrooms__gte=bedroom_filter_min)
        if bedroom_filter_max:
            # Filter properties with number of bedrooms less than or equal to the maximum specified
            active_props = active_props.filter(imb_Bedrooms__lte=bedroom_filter_max)

    # Prepare context to pass to template
    context = {
        "imgs": imgs,  # Pass images
        "props": active_props,  # Pass filtered properties
        "cities": cities,  # Pass city options for dropdown
        "property_types": property_types,  # Pass property type options for dropdown
        "bedroom_filter_min": bedroom_filter_min,  # Pass minimum bedroom filter value
        "bedroom_filter_max": bedroom_filter_max,  # Pass maximum bedroom filter value
    }

    # Render the template with the context
    return render(request, "web_site/portfolio.html", context)


def portfolio_es(request):
    # Obtener imágenes
    imgs = PropertyImage.objects.all()
    # Obtener valores distintos para cada menú desplegable
    cities = SMRTPROPERTIES.objects.filter(imb_Active=True).values_list('imb_City', flat=True).distinct()
    property_types = SMRTPROPERTIES.objects.filter(imb_Active=True).values_list('imb_Type', flat=True).distinct()

    # Filtrar propiedades según la entrada del usuario
    if request.method == 'GET':
        location_filter = request.GET.get('location_filter')
        property_type_filter = request.GET.get('property_type_filter')
        # Agregar más filtros para otros menús desplegables según sea necesario

        active_props = SMRTPROPERTIES.objects.filter(imb_Active=True)
        if location_filter:
            active_props = active_props.filter(imb_City=location_filter)
        if property_type_filter:
            active_props = active_props.filter(imb_Type=property_type_filter)
        # Agregar más filtros para otros menús desplegables según sea necesario

    context = {
        "imgs": imgs,
        "props": active_props,
        "cities": cities,
        "property_types": property_types,
        # Agregar más para otros menús desplegables según sea necesario
    }
    return render(request, "web_site/portfolio_es.html", context)


def contact_es(request):
    form = SMRTWEBFORMForm()  # Define form outside the conditional block
    
    if request.method == 'POST':
        form = SMRTWEBFORMForm(request.POST)
        if form.is_valid():
            form.instance.frm_date = datetime.now()
            form.save()
            return redirect('contact_es')  # Redirect to a success page
    
    return render(request, "web_site/contact_es.html", {'form': form})

def faqs(request):
    return render(request, "web_site/faqs.html")

def faqs_es(request):
    return render(request, "web_site/faqs_es.html")

def insurance_es(request):
   return render(request, "web_site/insurance_es.html")

def accountant_es(request):
   return render(request, "web_site/accountant_es.html")

def insurance(request):
   return render(request, "web_site/insurance.html")

def accountant(request):
   return render(request, "web_site/accountant.html")

smart_web/web_site/templates/web_site/contact.html
{% extends "web_site/layout.html" %}
{% block content%}
<!-- contact section -->
<section class="contact_section ">
    <div class="container-fluid">

      <div class="row">
        <div class="col-md-6 px-0">
          <div class="img-box ">
            <img src="/static/images/contact-img.jpg" class="box_img" alt="about img">
          </div>
        </div>
        <div class="col-md-5 mx-auto">
          <div class="form_container">
            <div class="heading_container heading_center">
              <h2>Get In Touch</h2>
            </div>
            
                
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="btn_box">
                  <button type="submit">SEND</button>
                </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- end contact section -->
{%endblock%}

smart_web/web_site/templates/web_site/portfolio.html
{% extends "web_site/layout.html" %}
{% block content%}
<script>
    $(document).ready(function() {
      $('.carousel').carousel({
        // Owl Carousel options here
      });
    });
  </script>
<div style="background-color: white;">
    <section class="team_section layout_padding">
        <div class="container">
            <div class="heading_container heading_center">
                <h2>Our Portafolio</h2>
                <p>Building and managing a diversified property portfolio requires strategic vision and proactive management. With Patrimonial Smart, we ensure that your investments thrive, offering customized solutions to optimize your real estate assets and ensure long-term growth.</p>
                <div class="search_bar form-row">
                    <form action="{% url 'portfolio' %}" method="get" class="container-fluid">
                        <input type="text" name="search" placeholder="Buscar...">
                        <select name="location_filter" id="location_filter">
                            <option value="">Any City...</option>
                            {% for city in cities %}
                            <option value="{{ city }}">{{ city }}</option>
                            {% endfor %}
                        </select>
                        <select name="property_type_filter" id="property_type_filter">
                            <option value="">Property Type</option>
                            {% for property_type in property_types %}
                            <option value="{{ property_type }}">{{ property_type }}</option>
                            {% endfor %}
                        </select>
                        <input class="form-control w-25" type="number" name="bedroom_filter_min" placeholder="Min Bedrooms" value="{{ bedroom_filter_min }}">
                        <input class="form-control w-25" type="number" name="bedroom_filter_max" placeholder="Max Bedrooms" value="{{ bedroom_filter_max }}">
                        <button type="submit">Filtrar</button>
                    </form>
                </div>
            </div>
            <div class="row">
                {% for prop in props %}
                <div class="col-md-4 col-sm-6 mx-auto">
                    <div class="box">
                        <div class="img-box">
                                <img src="{{ prop.propertyimage_set.first.image.url }}" alt="">
                        </div>
                        <div class="detail-box">
                            <h5>{{ prop.imb_Name }}</h5>
                            <h6>{{ prop.imb_State }}</h6>
                            <h6>{{ prop.imb_Description }}</h6>
                            <h6>{{ prop.imb_Price }}  {{ prop.imb_Currency }}</h6>
                            <button type="button" class="btn btn-warning" data-toggle="modal"  data-target="#exampleModal{{ prop.imb_ID }}">
                                View more
                            </button>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</div>

{% for prop in props %}
<div class="modal fade" id="exampleModal{{ prop.imb_ID }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{ prop.imb_ID }}" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel{{ prop.imb_ID }}">{{ prop.imb_Name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                
                <!-- image carousel -->
                <div id="carouselExampleControls{{ prop.imb_ID }}" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                    {% for image in prop.propertyimage_set.all %}
                      <div class="carousel-item {% if forloop.first %}active{% endif %}">
                        <img src="{{image.image.url}}" alt="" style="" class="w-100">
                      </div>                
                    {%endfor%}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls{{ prop.imb_ID }}" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="carousel-control-next" href="#carouselExampleControls{{ prop.imb_ID }}" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                      </a>
                </div>
            
                

                <!-- end image carousel -->





                <table class="table">
                    <tbody>
                        <tr>
                            <th scope="row">Category</th>
                            <td>{{ prop.imb_Category }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Name</th>
                            <td>{{ prop.imb_Name }}</td>
                        </tr>
                        <tr>
                            <th scope="row">MLS</th>
                            <td>{{ prop.imb_MLS }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Type</th>
                            <td>{{ prop.imb_Type }}</td>
                        </tr>
                        <tr>
                            <th scope="row">City</th>
                            <td>{{ prop.imb_City }}</td>
                        </tr>
                        <tr>
                            <th scope="row">State</th>
                            <td>{{ prop.imb_State }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Area</th>
                            <td>{{ prop.imb_Area }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Bedrooms</th>
                            <td>{{ prop.imb_Bedrooms }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Bathrooms</th>
                            <td>{{ prop.imb_Bathrooms }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Size</th>
                            <td>{{ prop.imb_Size }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Price</th>
                            <td>{{ prop.imb_Price }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Currency</th>
                            <td>{{ prop.imb_Currency }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Description</th>
                            <td>{{ prop.imb_Description }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <a href="{%url 'contact_es'%}" class="btn btn-primary" style="background-color: 0877bf;">Quiero saber Mas</a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
    </div>

{% endfor %}
<script>
  $(document).ready(function() {
    $('#carouselExampleIndicators-').carousel({
      // Owl Carousel options here
    });
  });
</script>
{% endblock %}

smart_web/web_site/templates/web_site/portfolio_es.html
{% extends "web_site/layout_es.html" %}  <!-- Extender el diseño principal -->

{% block content%}  <!-- Inicio del bloque de contenido -->
<script>
    $(document).ready(function() {
      $('.carousel').carousel({
        // Opciones de Owl Carousel aquí
      });
    });
</script>
<div style="background-color: white;">
    <section class="team_section layout_padding">
        <div class="container">
            <div class="heading_container heading_center">
                <h2>Nuestro Portafolio</h2>
                <p>Construir y gestionar un portafolio de propiedades diversificado requiere visión estratégica y gestión proactiva. Con Patrimonial Smart, aseguramos que tus inversiones prosperen, ofreciendo soluciones personalizadas para optimizar tus activos inmobiliarios y garantizar un crecimiento a largo plazo.</p>
                <div class="search_bar">
                    <form action="{% url 'portfolio' %}" method="get">
                        <input type="text" name="search" placeholder="Buscar...">
                        <select name="location_filter" id="location_filter">
                            <option value="">Todas las Ubicaciones</option>
                            {% for city in cities %}
                            <option value="{{ city }}">{{ city }}</option>
                            {% endfor %}
                        </select>
                        <select name="property_type_filter" id="property_type_filter">
                            <option value="">Tipo de Propiedad</option>
                            {% for property_type in property_types %}
                            <option value="{{ property_type }}">{{ property_type }}</option>
                            {% endfor %}
                        </select>
                        <button type="submit">Filtrar</button>
                    </form>
                </div>
            </div>
            <div class="row">
                {% for prop in props %}
                <div class="col-md-4 col-sm-6 mx-auto">
                    <div class="box">
                        <div class="img-box">
                                <img src="{{ prop.propertyimage_set.first.image.url }}" alt="">
                        </div>
                        <div class="detail-box">
                            <h5>{{ prop.imb_Name }}</h5>
                            <h6>{{ prop.imb_State }}</h6>
                            <h6>{{ prop.imb_Description }}</h6>
                            <h6>{{ prop.imb_Price }}  {{ prop.imb_Currency }}</h6>
                            <button type="button" class="btn btn-warning" data-toggle="modal"  data-target="#exampleModal{{ prop.imb_ID }}">
                                Ver más
                            </button>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</div>

{% for prop in props %}
<div class="modal fade" id="exampleModal{{ prop.imb_ID }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{ prop.imb_ID }}" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel{{ prop.imb_ID }}">{{ prop.imb_Name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                
                <!-- Carrusel de imágenes -->
                <div id="carouselExampleControls{{ prop.imb_ID }}" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                    {% for image in prop.propertyimage_set.all %}
                      <div class="carousel-item {% if forloop.first %}active{% endif %}">
                        <img src="{{image.image.url}}" alt="" style="" class="w-100">
                      </div>                
                    {%endfor%}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls{{ prop.imb_ID }}" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Anterior</span>
                      </a>
                      <a class="carousel-control-next" href="#carouselExampleControls{{ prop.imb_ID }}" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Siguiente</span>
                      </a>
                </div>
            
                

                <!-- Fin del carrusel de imágenes -->





                <table class="table">
                    <tbody>
                        <tr>
                            <th scope="row">Categoría</th>
                            <td>{{ prop.imb_Category }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Nombre</th>
                            <td>{{ prop.imb_Name }}</td>
                        </tr>
                        <tr>
                            <th scope="row">MLS</th>
                            <td>{{ prop.imb_MLS }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Tipo</th>
                            <td>{{ prop.imb_Type }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Ciudad</th>
                            <td>{{ prop.imb_City }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Estado</th>
                            <td>{{ prop.imb_State }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Área</th>
                            <td>{{ prop.imb_Area }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Habitaciones</th>
                            <td>{{ prop.imb_Bedrooms }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Baños</th>
                            <td>{{ prop.imb_Bathrooms }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Tamaño</th>
                            <td>{{ prop.imb_Size }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Precio</th>
                            <td>{{ prop.imb_Price }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Moneda</th>
                            <td>{{ prop.imb_Currency }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Descripción</th>
                            <td>{{ prop.imb_Description }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <a href="{%url 'contact_es'%}" class="btn btn-primary" style="background-color: 0877bf;">Quiero saber Más</a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
    </div>

{% endfor %}
<script>
  $(document).ready(function() {
    $('#carouselExampleIndicators-').carousel({
      // Opciones de Owl Carousel aquí
    });
  });
</script>
{% endblock %}